LigaData/Kamanja

trunk/KamanjaBase/src/main/scala/com/ligadata/KamanjaBase/ModelBase.scala, trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/ExecContext.scala, trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/LearningEngine.scala
Added new field called msgData of type Array[Byte] in ModelContext. Also added 3 functions to ModelContext
1. Function InputMessageData will get the the msgData associated to the current message of type Array[Byte]. This will be used when someone want to see the original raw data for the given message (msg)
2. Funtion Message will return the msg of type MessageContainerBase. That is the current deserialized message from the input raw-data.
3. Function TransactionContext returns the txnContext in model context
=> Making sure the input data is available for the data through ModelContext

trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/ExecContext.scala, trunk/KamanjaUtils/src/main/scala/com/ligadata/Utils/ClassLoaderInfo.scala
2. Setting KamanjaClassLoader to Thread.currentThread().setContextClassLoader before we process any message/event, if it changed
=> 1. Override getResource & getResources functions in KamanjaClassLoader

trunk/.gitignore, trunk/MetadataAPI/src/main/resources/HelpMenu.txt, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/StartMetadataAPI.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/ContainerService.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/MessageService.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/ModelService.scala, trunk/SampleApplication/EasyInstall/SetPaths.sh
This branch will have 2-3 more code changes related to kamanja command line as well
=> Help menu updated with correct command dump all cluster config

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MonitorAPIImpl.scala
@ligadata-william rebased on DEV
=> Trace a stack if HB encounters and exception

trunk/InputOutputAdapters/FileSimpleInputOutputAdapters/src/main/scala/com/ligadata/OutputAdapters/FileProducer.scala, trunk/SampleApplication/EasyInstall/easyInstallKamanja.sh, trunk/build.sbt
@ligadata-william 
Give it Merle love
=> Add error recovery to the File Producer

trunk/Storage/HBase/src/main/scala/com/ligadata/keyvaluestore/HBaseAdapter.scala, trunk/Storage/HBase/src/test/resources/log4j2.xml, trunk/Storage/HBase/src/test/scala/HBaseAdapaterSpec.scala, trunk/Storage/HBase/src/test/scala/HBasePerfTestSpec.scala
I have pulled the hbase adapter changes from StorageExceptions  into this branch. Pokuri wants this to be merged into dev branch..
=> HBase Adapter Issues with 1.2

trunk/Storage/SqlServer/build.sbt, trunk/Storage/SqlServer/src/main/scala/com/ligadata/keyvaluestore/SqlServerAdapter.scala, trunk/Storage/SqlServer/src/test/resources/log4j2.xml, trunk/Storage/SqlServer/src/test/scala/SimulateDeadlockSpec.scala, trunk/Storage/SqlServer/src/test/scala/SqlServerAdapterSpec.scala, trunk/Storage/SqlServer/src/test/scala/SqlServerPerfTestSpec.scala
Not sure why it can't be merged automatically. Let me know if you have any trouble merging these changes. These changes address deadlock issue with sqlserver.
=> Sql server deadlocks

trunk/MetadataAPI/src/main/resources/HelpMenu.txt
no menu style interaction with the pmml add and update...
=> Issue #914 Fix cmd documentation

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/StartMetadataAPI.scala
Bad commands now print like this:
Example:
rich@kobi:/tmp/drdigital$ bin/kamanja blah blah
Invalid command action! action=blahblah
Usage:
kamanja <action> <optional input>
e.g. kamanja add message $HOME/msg.json
=> Issue #916 Alternate parser noise eliminated

trunk/Utils/Script/kamanja
Added "kamanja watch failed events queue" command to script
=> Added kamanja watch failed events queue command to script

trunk/SampleApplication/EasyInstall/easyInstallKamanja.sh
scala-reflect-2.11.2.jar => scala-reflect-2.11.7.jar
scala-xml_2.11-1.0.2.jar => scala-xml_2.11-1.0.4.jar
remove slf4j-api-1.7.5-sources.jar
=> changing in EasyInstallKamanja script

trunk/EnvContexts/SimpleEnvContextImpl/src/main/scala/com/ligadata/SimpleEnvContextImpl/SimpleEnvContextImpl.scala, trunk/Exceptions/src/main/resources/Version.txt
GetMsgContainerElseNew is failing when we refer a container when the container not found in Get and while creating the new instance of that container.
Attaching the sample application used.
[EmpAppData.csv.txt](https://github.com/ligaDATA/Kamanja/files/106270/EmpAppData.csv.txt)
[employeeCont.json.txt](https://github.com/ligaDATA/Kamanja/files/106269/employeeCont.json.txt)
[EmployeeMdlt.xml.txt](https://github.com/ligaDATA/Kamanja/files/106271/EmployeeMdlt.xml.txt)
[EmployeeMsg.json.txt](https://github.com/ligaDATA/Kamanja/files/106272/EmployeeMsg.json.txt)
=> Using class loader if it present to resolve the container/message in kPMML function

trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/AddModelService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/MetadataAPIService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/UpdateModelService.scala
Calling KPMML API instead of  PMML API
=> fixing Issue930

trunk/Utils/Migrate/DestinationVersion/MigrateTo_V_1_3/src/main/scala/com/ligadata/Migrate/MigrateTo.scala, trunk/Utils/Migrate/MigrateBase/src/main/java/com/ligadata/MigrateBase/MigratableFrom.java, trunk/Utils/Migrate/MigrateBase/src/main/java/com/ligadata/MigrateBase/MigratableTo.java, trunk/Utils/Migrate/MigrateManager/src/main/java/com/ligadata/Migrate/Migrate.java, trunk/Utils/Migrate/MigrateManager/src/main/resources/MigrateConfig.json, trunk/Utils/Migrate/SourceVersion/MigrateFrom_V_1_1/src/main/scala/com/ligadata/Migrate/MigrateFrom.scala, trunk/Utils/Migrate/SourceVersion/MigrateFrom_V_1_2/src/main/scala/com/ligadata/Migrate/MigrateFrom.scala
Fixed couple of issues found in Migration testing.
=> Migration fixes

trunk/Storage/HBase/src/main/scala/com/ligadata/keyvaluestore/HBaseAdapter.scala, trunk/Utils/Migrate/MigrateManager/src/main/java/com/ligadata/Migrate/Migrate.java
Creating destination table in copy command and using Scan & Put to copy the table from source to destination
=> HBase backup fix

trunk/InputOutputAdapters/KafkaSimpleInputOutputAdapters/src/main/scala/com/ligadata/InputAdapters/KafkaSimpleConsumer.scala, trunk/InputOutputAdapters/KafkaSimpleInputOutputAdapters/src/main/scala/com/ligadata/OutputAdapters/KafkaProducer.scala
=> synck up monitor writing metrics to the output adapter

trunk/SampleApplication/HelloWorld/template/script/HelloWorldApp_Template.sh, trunk/Utils/Script/kamanja
Changed the way we search for the process ID of KamanjaManager to work on linux.
=> Changed add model pmml to add model kpmml in HelloWorldApp.sh

trunk/SampleApplication/EasyInstall/SetPaths.sh, trunk/Utils/Script/kamanja
Add certificate and shebang to Setpaths to avoid permission issues
=> Add certificate and shebang to Setpaths to avoid permission issues

trunk/FileDataConsumer/src/main/scala/com/ligadata/filedataprocessor/FileProcessor.scala, trunk/FileDataConsumer/src/main/scala/com/ligadata/filedataprocessor/KafkaMessageLoader.scala
@ligadata-sridhar 
This the code code based on Berkley.. you already have the Jar file based on this. 
Dans-MacBook-Pro-2:tmp dankozin$ scp -i /Users/dankozin/Kamanja-POC.pem  /Users/dankozin/kamanjaSrc/trunk/FileDataConsumer/target/scala-2.10/FileDataConsumer-0.1.0 root@54.159.38.198:/opt/from-DANK
FileDataConsumer-0.1.0                                                                                           100%   77MB   2.9MB/s   00:27
Dans-MacBook-Pro-2:tmp dankozin$
=> make BROKEN_FILES into CORRUPTED_FILES to make them fail without retry

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ErrorCodeConstants.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MessageAndContainerUtils.scala
=> 1.4.0.test.1112a

trunk/Utils/Script/scala-2.10/kamanja, trunk/Utils/Script/scala-2.11/kamanja
=> 1063 ensured kamanja process exited

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/StartMetadataAPI.scala
=> 1.4.0.1116

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MessageAndContainerUtils.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ModelUtils.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/ContainerService.scala
=> 1.5.0.1118

trunk/MetadataAPI/src/main/resources/HelpMenu.txt, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/AddAdapterMessageBindingsService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/GetAdapterMsgBindingsService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/GetAllObjectKeysService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/MetadataAPIService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/RemoveAdapterMsgBindingsService.scala, trunk/build.sbt
=> Adapter msg binding rest

trunk/MetadataAPI/src/test/scala/TestGenerateUniqueId.scala, trunk/Utils/Migrate/DestinationVersion/MigrateTo_V_1_4/src/main/scala/com/ligadata/Migrate/MigrateTo.scala
Merge this into 1.4.1 after validation
=> Make sure unique modelconfig files are generated during migration

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MessageAndContainerUtils.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ModelUtils.scala
=> 1119/ added code to prevent adding objects when they are added already

trunk/MessageCompiler/src/test/scala/com/ligadata/testmsgcompiler/MessageCompilerTestSuite.scala, trunk/MetadataAPI/src/test/resources/Metadata/config/ClusterConfig.json, trunk/MetadataAPI/src/test/resources/Metadata/config/sample_adapters.json, trunk/MetadataAPI/src/test/scala/AddModelSpec.scala, trunk/MetadataAPI/src/test/scala/ContainerAPISpec.scala, trunk/MetadataAPI/src/test/scala/MetadataAPISerializationTest.scala, trunk/MetadataAPI/src/test/scala/MigrateAdapterSpec.scala, trunk/Storage/Cassandra/src/test/scala/CassandraAdapterSpec.scala, trunk/Storage/HBase/src/test/scala/HBaseTestMetadataContainersSpec.scala, trunk/Storage/HBase/src/test/scala/HBaseTestMetadataFlagSpec.scala, trunk/Storage/HBase/src/test/scala/TestGetAllTablesSpec.scala, trunk/Storage/SqlServer/src/test/scala/SqlServerAdapterSpec.scala
Fixes for various unit tests. Three unit tests still fail due to issues in code.
=> Fix unit tests 1.5

trunk/MetadataAPI/src/main/resources/HelpMenu.txt, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ErrorCodeConstants.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MessageAndContainerUtils.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MetadataAPIImpl.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/StartMetadataAPI.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/TestMetadataAPI.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/Action.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/TypeService.scala, trunk/MetadataAPI/src/test/resources/Metadata/config/ClusterConfig.json, trunk/MetadataAPI/src/test/scala/MigrateAdapterSpec.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/AddAdapterMessageBindingsService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/GetAdapterMsgBindingsService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/GetAllObjectKeysService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/GetObjectsService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/GetTypeByIdService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/MetadataAPIService.scala, trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/RemoveAdapterMsgBindingsService.scala, trunk/MetadataAPIServiceClient/src/main/scala/com/ligadata/metadataapiserviceclient/TestApiService.scala, trunk/Utils/Migrate/GenerateAdapterBindings/src/main/scala/com/ligadata/GenerateAdapterBindings/GenerateAdapterBindings.scala, trunk/build.sbt
Pull request for Issues 1067 and 1068
=> Kamanja1067

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ModelUtils.scala
=> 1119 fixed model issue

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/ModelService.scala
=> fix to return json api string for get models

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MessageAndContainerUtils.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/TypeUtils.scala, trunk/MetadataAPI/src/test/scala/AddContainerSpec.scala, trunk/MetadataAPI/src/test/scala/ContainerAPISpec.scala
Used MetadataAPI/src/test/scala/AddContainerSpec  to test this
=> 1.5.0.1133

trunk/MetadataAPI/src/main/resources/HelpMenu.txt, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/StartMetadataAPI.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/AlternateCmdParser.scala
Remove Alternate command parser usage from Metadata API code and update the help menu.
=> Kamanja 1035

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/CompilerProxy.scala
=> created to resolve issue #772

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MetadataAPIImpl.scala
issue is : https://github.com/LigaData/Kamanja/issues/619
a new exception was added.
=> adding an exception for empty string

trunk/ExtDependencyLibs2/build.sbt, trunk/Utils/Cache/src/main/java/com/ligadata/cache/CacheCallbackData.java, trunk/Utils/Cache/src/main/java/com/ligadata/cache/DataCache.java, trunk/Utils/Cache/src/main/scala/com/ligadata/cache/Config.scala, trunk/Utils/CacheImp/src/main/scala/com/ligadata/cache/CacheCustomConfig.scala, trunk/Utils/CacheImp/src/main/scala/com/ligadata/cache/MemoryDataCacheImp.scala, trunk/Utils/CacheImp/src/main/scala/com/ligadata/cache/infinispan/CacheCustomConfig.scala, trunk/Utils/CacheImp/src/main/scala/com/ligadata/cache/infinispan/EventCacheListener.scala, trunk/Utils/CacheImp/src/main/scala/com/ligadata/cache/infinispan/MemoryDataCacheImp.scala, trunk/Utils/CacheImp/src/main/scala/com/ligadata/cache/infinispan/MemoryDataWithoutTreeCacheImp.scala, trunk/Utils/CacheImp/src/test/scala/InfiniNode.scala, trunk/Utils/CacheImp/src/test/scala/InfiniNode2.scala, trunk/Utils/CacheImp/src/test/scala/InfiniNodeWithoutCache.scala
this contain the tree cache implementation for infinispan.
=> Hierarchicalcache

trunk/SampleApplication/EasyInstall/template/scala-2.10/config/ClusterConfig_Template.json, trunk/SampleApplication/EasyInstall/template/scala-2.10/config/EngineConfig_Template.properties, trunk/SampleApplication/EasyInstall/template/scala-2.10/config/MetadataAPIConfig_Template.properties, trunk/SampleApplication/EasyInstall/template/scala-2.10/script/StartH2dbServer_Template.sh, trunk/SampleApplication/EasyInstall/template/scala-2.11/config/ClusterConfig_Template.json, trunk/SampleApplication/EasyInstall/template/scala-2.11/config/EngineConfig_Template.properties, trunk/SampleApplication/EasyInstall/template/scala-2.11/config/MetadataAPIConfig_Template.properties, trunk/SampleApplication/EasyInstall/template/scala-2.11/script/StartH2dbServer_Template.sh, trunk/Storage/H2DB/src/main/scala/com/ligadata/keyvaluestore/H2dbAdapter.scala
=> 1.5.0 kamanja 642

trunk/ExtDependencyLibs2/build.sbt, trunk/Utils/CacheImp/src/main/scala/com/ligadata/cache/infinispan/MemoryDataCacheImp.scala, trunk/Utils/CacheImp/src/main/scala/com/ligadata/cache/infinispan/MemoryDataWithoutTreeCacheImp.scala, trunk/Utils/CacheImp/src/test/scala/InfiniNode.scala, trunk/Utils/CacheImp/src/test/scala/InfiniNode2.scala, trunk/Utils/CacheImp/src/test/scala/InfiniNodeWithoutCache.scala
java.lang.AssertionError: assertion failed:
net.jcip.annotations.Immutable
=> fix the build problem

trunk/FileDataConsumer/src/main/scala/com/ligadata/filedataprocessor/FileProcessor.scala, trunk/FileDataConsumer/src/main/scala/com/ligadata/filedataprocessor/KafkaMessageLoader.scala, trunk/FileDataConsumer/src/main/scala/com/ligadata/filedataprocessor/SmartFileAdapterConstants.scala
Meging file consumer changes made in other versions
=> 1.5.0.file data consumer

trunk/InputOutputAdapters/SmartFileAdapter/src/main/scala/com/ligadata/OutputAdapters/SmartFileProducer.scala
Fix getComponentSimpleStats and time partition logic
=> Fix getComponentSimpleStats and time partition logic

trunk/KamanjaUI/Rest/KamanjaUIRest/build.sbt, trunk/KamanjaUI/Rest/KamanjaUIRest/src/resources/KamanjaUIVersion.txt, trunk/KamanjaUI/UI/KamanjaUIVersion.txt, trunk/SampleApplication/EasyInstall/easyInstallKamanja.sh
1. Added KamanjaUIVersion.txt
2. Copying UI destro
=> Added KamanjaUIVersion.txt for UI projects & changed easyInstall

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/AdapterMessageBindingUtils.scala, trunk/Utils/AdapterSerializers/JsonSerDeser/src/main/scala/com/ligadata/kamanja/serializer/JsonSerDeser.scala
2. Fixed Maps serializing into JSON.
=> 1. Handled JSON Tagged Messages in Deserialization

trunk/Metadata/src/main/scala/com/ligadata/kamanja/metadata/mdelems.scala, trunk/Metadata/src/main/scala/com/ligadata/kamanja/metadata/mdmgr.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ConfigUtils.scala
@ligadata-pokuri 
This is bases on dev as per our discussion.
=> 1.5.1.1351

trunk/EnvContexts/SimpleEnvContextImpl/src/main/scala/com/ligadata/SimpleEnvContextImpl/SimpleEnvContextImpl.scala, trunk/KamanjaBase/src/main/scala/com/ligadata/KamanjaBase/ModelBase.scala, trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/ExecContext.scala, trunk/SampleApplication/EasyInstall/easyInstallKamanja.sh, trunk/SampleApplication/EasyInstall/easyInstallKamanjaExperimental.sh, trunk/Utils/SaveContainerDataComponent/src/main/scala/com/ligadata/tools/SaveContainerDataComponent.scala
Has the following fixes
1. Setting Default SerializerDeserializer in SaveContainerDataComponent
2. Copying savecontainerdatacomponent jar into lib/system
3. Supporting to control commits with forcecommit in TransactionContext & EnableEachTransactionCommit in ClusterConfig.json. By default forcecommit is false & EnableEachTransactionCommit is true
4. Bug fix in Caching containers  for the new containers generated in Engine.
=> 1.5.1.saving controls

trunk/FileDataConsumer/src/main/scala/com/ligadata/filedataprocessor/FileProcessor.scala, trunk/Metadata/src/main/scala/com/ligadata/kamanja/metadata/mdmgr.scala
@ligadata-pokuri @ligadata-haitham 
Hi guys this is the fix for the ^C that was being ignored if there is a configuration issue.  Pokuri and I reviewed the code briefly.
=> Kamanja872

trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/ExecContext.scala, trunk/Utils/ContainersUtility/src/main/scala/com/ligadata/tools/containersutility/ContainersUtility.scala
Fix for bug#https://github.com/LigaData/Kamanja/issues/1394
=> 1.5.1 phoenix primarykeyfix

trunk/FileDataConsumer/src/main/scala/com/ligadata/filedataprocessor/KafkaMessageLoader.scala, trunk/FileDataConsumer/src/main/scala/com/ligadata/filedataprocessor/SmartFileAdapterConstants.scala
=> add changes for Kafka Message Size check

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/StartMetadataAPI.scala
Reorder the exceptions based on the hierarchy in StartMetadataAPI.
=> Exception handling in StartMetadataAPI

trunk/SampleApplication/EasyInstall/template/scala-2.10/script/StartEngine_Template.sh, trunk/SampleApplication/EasyInstall/template/scala-2.11/script/StartEngine_Template.sh, trunk/Utils/Script/scala-2.10/kamanja, trunk/Utils/Script/scala-2.11/kamanja
Pass custom engine config to kamanja start engine.
=> Pass custom engine config to kamanja start engine: Github1159

trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ErrorCodeConstants.scala, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/StartMetadataAPI.scala
Result's constants value updated for 'dump all nodes'
=> Result's constants value updated for 'dump all nodes'

trunk/ExtDependencyLibs2/build.sbt, trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/Utility/ModelService.scala, trunk/Utils/Migrate/MigrateManager/build.sbt
Git1418: API result to be returned for Pythoin, Jython and PMML
=> API result to be returned for Pythoin, Jython and PMML

trunk/Utils/OutputUtils/src/main/java/com/ligadata/tools/validator/KafkaClientPropValidator.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/tools/validator/PropertiesValidator.java
Validator for kafka client properties added to the OutputUtils, KAFKA TO HDFS, KamanjaEndpointServices
=> Validator for kafka client properties

trunk/Utils/OutputUtils/pom.xml, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/AdapterConfiguration.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/BufferedMessageProcessor.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/MessageConsumer.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/NullProcessor.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/StatusCollectable.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/container/AITUserDailyProfileSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/container/DedupContainerSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/container/DqContainerSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/container/FileStatusSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/hdfs/BufferedPartitionedAvroSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/AbstractJDBCSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/BufferedJDBCSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkInsertSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/UpsertJDBCSink.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/mail/BufferedMailProcessor.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/statusRecorders/KafkaStatusRecorder.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/tools/validator/KafkaClientPropValidator.java, trunk/Utils/OutputUtils/src/main/java/com/ligadata/tools/validator/PropertiesValidator.java, trunk/Utils/OutputUtils/src/test/java/com/ligadata/test/SqlServerBulkTest.java, trunk/Utils/ZooKeeper/CuratorClient/src/main/scala/com/ligadata/ZooKeeper/CreateClient.scala
Kamanja Endpoint services for Kafka-HDFS/SQL's statistics logging into kafka
=> End point tools status into kafka

trunk/InputOutputAdapters/ElasticsearchAdapters/src/main/scala/com/ligadata/ElasticsearchInputOutputAdapters/ElasticsearchProducer.scala, trunk/Storage/Elasticsearch/src/main/scala/com/ligadata/keyvaluestore/Elasticsearch.scala
Caching data before flushing. For now it has hard coded values like 60 secs data collection or 1000 records.
=> Berkley 1.5.3 adapter changes es fixes

trunk/InputOutputAdapters/ElasticsearchAdapters/src/main/scala/com/ligadata/ElasticsearchInputOutputAdapters/ElasticsearchProducer.scala
1. Added timer flush. This checks for every sec whether it met condition to flush or not
2. Cleaned up lot of unnecessary code
3. Added processed counters
=> 1. Added Timer flush. 

trunk/SampleApplication/EasyInstall/easyInstallKamanjaExperimental.sh, trunk/Utils/KamanjaAppTester/src/main/resources/script/2.10/RunApplicationTests_Template.sh, trunk/Utils/KamanjaAppTester/src/main/resources/script/2.11/RunApplicationTests_Template.sh, trunk/Utils/KamanjaAppTester/src/main/scala/com/ligadata/kamanja/test/application/configuration/KamanjaApplicationConfiguration.scala, trunk/Utils/KamanjaAppTester/src/test/resources/kamanjaInstall/test/TestApp1/ApplicationConfiguration.json
Implemented the json syntax for datasets as described in the task
=> FLR-275, support a more flexible structure for DataSet definitions

trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/ExecContext.scala
Introduced PostSystemMessageList in ClusterConfig to post com.ligadata.KamanjaBase.KamanjaMessageEvent to queue so that some models can depend on com.ligadata.KamanjaBase.KamanjaMessageEvent.
In ClusterConfig.json it looks like this
{
"Clusters": [
{
"ClusterId": "ligadata1",
"PostSystemMessageList": "com.ligadata.KamanjaBase.KamanjaMessageEvent",
"SystemCatalog": {
............
=> 1.6.2.test.post system msg

trunk/Utils/AdapterSerializers/CsvSerDeser/src/main/scala/com/ligadata/kamanja/serializer/CsvSerDeser.scala
=> Berkley 1.5.3 adapterChanges csvformater

trunk/InputOutputAdapters/ElasticsearchAdapters/src/main/scala/com/ligadata/ElasticsearchInputOutputAdapters/ElasticsearchProducer.scala, trunk/InputOutputAdapters/SmartFileAdapter/src/main/scala/com/ligadata/InputAdapters/MonitorController.scala
1. Added some log in Monitor thread for every 1000 secs if logger deb…ug is not enabled & warn is enabled
2. Introduced MaxRetriesForIllegalArgumentException to retry IllegalArgumentException. By default it will retry only 3 times. That is only for this exception & the message contains "Document contains at least one immense term in field"
=> Logs & exception handling

trunk/EnvContexts/SimpleEnvContextImpl/src/main/scala/com/ligadata/SimpleEnvContextImpl/SimpleEnvContextImpl.scala, trunk/KamanjaBase/src/main/scala/com/ligadata/KamanjaBase/ModelBase.scala, trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/KamanjaLeader.scala
=> Revert "1.5.3 phoenix flr 304 574"

trunk/EnvContexts/SimpleEnvContextImpl/src/main/scala/com/ligadata/SimpleEnvContextImpl/SimpleEnvContextImpl.scala, trunk/InputOutputAdapters/SmartFileAdapter/src/main/scala/com/ligadata/InputAdapters/SmartFileConsumer.scala, trunk/KamanjaBase/src/main/scala/com/ligadata/KamanjaBase/ModelBase.scala, trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/KamanjaLeader.scala
These changes are related to FLR 304 & 574. Previous pull requests are https://github.com/LigaData/Kamanja/pull/1521 & https://github.com/LigaData/Kamanja/pull/1522.
Changing the NodeId & UUID from JSON to simple string fixed Input adapter issue for now.
=> 1.5.3 phoenix p iib flr 304 574

trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/MetadataAPIService.scala
Getting messages also in daas api
=> 1.5.3-phoenix-daas-api-input-md-move-issue-1562

trunk/InputOutputAdapters/JDBCAdapters/build.sbt, trunk/InputOutputAdapters/JDBCAdapters/project/plugins.sbt, trunk/InputOutputAdapters/JDBCAdapters/readme.txt, trunk/InputOutputAdapters/JDBCAdapters/src/main/resources/TestConfig.json, trunk/InputOutputAdapters/JDBCAdapters/src/main/scala/com/ligadata/AdapterConfiguration/DbAdapterConfiguration.scala, trunk/InputOutputAdapters/JDBCAdapters/src/main/scala/com/ligadata/InputAdapters/DbConsumer.scala, trunk/build.sbt
JDBC Input Adapter changes (Changes from 1.5.3-phoenix-P-IIB-FLR-604 are copied, because 1.5.3-phoenix-P-IIB-FLR-604 can not merge into 1.5.3-phoenix-P-IIB anymore)
=> JDBC Input Adapter changes (Changes from 1.5.3-phoenix-P-IIB-FLR-604)

trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/AdapterPartitionInfoUtil.scala, trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/ExecContext.scala, trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/KamanjaLeader.scala
Changed logic for consolidation a bit
=> 1.5.3 phoenix fall back partition storage
